version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.14
    - 7.13.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.11.1
    - 4.14.1
    - 4.15.2
    - 4.20.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.1
    - 4.15.2
    - 4.20.0
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
    - 2.32.8
  - dependency-name: "@types/react"
    versions:
    - 16.14.4
    - 17.0.0
  - dependency-name: netlify-cli
    versions:
    - 2.69.11
    - 2.71.0
    - 3.4.6
  - dependency-name: webpack
    versions:
    - 5.11.1
    - 5.19.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: markdownlint-cli
    versions:
    - 0.26.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: object-path
    versions:
    - 0.11.5
