trigger:
    branches:
        include:
            - master
            - azure_pipelines

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: yarn install
      displayName: 'Install dependencies'

    - script: yarn build
      displayName: 'Build Gatsby'

    - task: CopyFiles@2
      inputs:
          sourceFolder: '$(System.DefaultWorkingDirectory)'
          contents: |
              public/**/*
          targetFolder: '$(Build.ArtifactStagingDirectory)'
          overWrite: true
      displayName: 'Copying built static files'

    - task: PublishBuildArtifacts@1
      inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'
          publishLocation: 'Container'
