Title: 'Ankur Sheel'
Description: 'I go down rabbit holes and blog about them'
Host: 'www.ankursheel.com'
LinksUseHttps: true
TwitterUsername: 'ankur_sheel'
GithubUsername: 'AnkurSheel'
LinkedInUsername: 'ankursheel'
BuyMeACoffeeUsername: 'ankursheel'
ReadingTimeWordsPerMinute: 238
NumberOfRelatedPosts: 4
HeaderLinks:
    - Title: 'About'
      Children:
        - Title: 'About'
          Url: '/about'
        - Title: 'Impossible List'
          Url: '/impossible-list'
        - Title: 'Book Summaries'
          Url: 'https://www.discoveriesinbookland.com/'
    - Title: 'Blog'
      Url: '/blog'
    - Title: 'Tags'
      Url: '/tags'
    - Title: 'CV'
      Url: '/cv'
    - Title: 'Contact'
      Url: '/contact'
#GoogleTagManagerId: GTM-MG9PGWH
GoatCounterCode: ankursheel
#icon: 'content/images/avatar.png',
#headerTitle: 'Home',
#webMonetization: '$ilp.uphold.com/FpRgJHkQhkhb',
#donateText: 'Did you learn something or find this article interesting?',
#buyMeACoffee: {
#  link: 'https://www.buymeacoffee.com/ankursheel',
#  altText: 'Buy me a coffee',
