backend:
    name: git-gateway
    branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
    - name: blog
      extension: mdx
      format: frontmatter
      label: Blog
      folder: 'content/posts'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
