name: 'PR $(System.PullRequest.PullRequestId)'

trigger:
    batch: false
    branches:
        exclude:
            - '*'
pr:
    autoCancel: false
    branches:
        include:
            - master

jobs:
    - template: azure-pipelines.common.yml
