parameters:
    deployScriptParams: '' # defaults for any parameters that aren't specified
    netlifySiteId: 'defaultID'
    netlifyToken: 'defaultToken'
    message: ''

jobs:
    - job: Build_And_Deploy

      pool:
          vmImage: 'ubuntu-latest'

      steps:
          # - checkout: self
          #   lfs: true

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '12.x'

          - task: Cache@2
            inputs:
                key: '15Apr21 | yarn | "$(Agent.OS)" | yarn.lock'
                restoreKeys: |
                    15Apr21 | yarn | "$(Agent.OS)" | yarn.lock
                path: $(YARN_CACHE_FOLDER)
            displayName: Cache Yarn packages

          - task: Cache@2
            inputs:
                key: '15Apr21 | gatsby | "$(Agent.OS)" | cache'
                restoreKeys: |
                    15Apr21 | gatsby | "$(Agent.OS)" | cache
                path: $(GASTBY_CACHE_FOLDER)
            displayName: Cache Gatsby Cache Folder

          - task: Cache@2
            inputs:
                key: '15Apr21 | gatsby | "$(Agent.OS)" | public'
                restoreKeys: |
                    15Apr21 | gatsby | "$(Agent.OS)" | public
                path: $(GASTBY_PUBLIC_FOLDER)
            displayName: Cache Gatsby Public Folder

          - script: yarn install --frozen-lockfile
            displayName: 'Install dependencies'

          - script: yarn build
            displayName: 'Build Gatsby'

          # prettier-ignore
          - script: |
              DEPLOY_URL=`yarn netlify deploy --site ${{ parameters.netlifySiteId }} --auth ${{ parameters.netlifyToken }} ${{ parameters.deployScriptParams }} --dir=public --json | jq --slurp --raw-input --raw-output 'split("\n") | .[5] | split("\"") | .[3]'`
              # DEPLOY_URL="https://$DEPLOY_ID--ankursheel.netlify.com/"
              echo "##vso[task.setvariable variable=DEPLOY_URL;isOutput=true]$DEPLOY_URL"
            displayName: 'Deploy to Netlify'
            name: deployToNetlify
