name: 'Release'

trigger:
    batch: false
    branches:
        include:
            - master

pr: none

jobs:
    - template: azure-pipelines.common.yml
      parameters:
          deployScriptParams: '--prod'
          netlifySiteId: ${{variables.netlify.siteId}}
          netlifyToken: ${{variables.netlify.token}}
