parameters:
    deployScriptParams: '' # defaults for any parameters that aren't specified
    netlifySiteId: 'defaultID'
    netlifyToken: 'defaultToken'
    message: ''

jobs:
    - job: Build

      pool:
          vmImage: 'ubuntu-latest'

      steps:
          - checkout: self
            lfs: true

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '10.x'

          - script: yarn install
            displayName: 'Install dependencies'

          - script: yarn build
            displayName: 'Build Gatsby'

          # prettier-ignore
          - script: yarn netlify deploy --site ${{ parameters.netlifySiteId }} --auth ${{ parameters.netlifyToken }} --message ${{ parameters.message }} ${{ parameters.deployScriptParams }} --dir=public
            displayName: 'Deploy to Netlify'
