jobs:
    - job: Build

      pool:
          vmImage: 'ubuntu-latest'

      steps:
          - checkout: self
            lfs: true

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '10.x'

          - task: Cache@2
            displayName: Cache Yarn packages
            inputs:
                key: 'yarn | "$(Agent.OS)" | yarn.lock'
                path: 'node_modules'
                restoreKeys: |
                    yarn | "$(Agent.OS)"
                    yarn

          - script: yarn install
            displayName: 'Install dependencies'

          - script: yarn build
            displayName: 'Build Gatsby'
